linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - noctx
    - golint
    - rowserrcheck
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - asciicheck
    - goimports
    - maligned
    - misspell
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - scopelint
    - whitespace
    - goprintffuncname
    #- gomnd # Magic numbers are fine for this event
    - goerr113
    - nestif
    - exportloopref
    - exhaustive
    - sqlclosecheck
    - nolintlint

issues:
  exclude:
    - Using the variable on range scope .* in function literal
    - comment on exported var .* should be of the form .*
