name: build-all
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # install actions
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29

      # build
      - name: build app
        run: go build -o aoc .

      # validate
      - name: run unit tests
        run: go test ./...
      - name: run linter
        run: golangci-lint run

      # run
      - name: run all solutions
        run: time ./aoc all
